/// Flutter icons Icon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icon
///      fonts:
///       - asset: fonts/Icon.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class FlutterIcon {
  FlutterIcon._();

  static const _kFontFam = 'Icon';
  static const String? _kFontPkg = null;

  static const IconData leaf = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temperatire = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain_inv = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soil = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData humidity = IconData(0xeae4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plant = IconData(0xf4d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
